version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.2
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - save_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - tmp/zips
      - run:
          name: Run Tests
          command: |
            bundle exec rspec --profile 10 \
                              --format documentation \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
